INSERT INTO "groups" (name,enabled,created_at,updated_at)
VALUES ('Superuser', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Administrators', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Operators', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Restore Users', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
       ('Backup Users', TRUE, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);